apiVersion: propertymappingprovider.authentik.crossplane.io/v1alpha1
kind: Scope
metadata:
  annotations:
    meta.upbound.io/example-id: propertymappingprovider/v1alpha1/scope
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    expression: |
      return {
        "policy": "readwrite",
      }
    name: minio
    scopeName: minio
