/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	resource "github.com/crossplane/upjet/pkg/resource"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/vhdirk/provider-authentik/apis/authentik/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Password.
func (mg *Password) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      resource.ExtractParamPath("uuid", true),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      resource.ExtractParamPath("uuid", true),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}
