/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorDuo) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorSMS) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorStatic) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorTOTP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorValidate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorWebAuthn) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Captcha) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Consent) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Deny) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Dummy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Email) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Identification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Invitation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Password) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Prompt) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PromptField) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserDelete) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserLogin) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserLogout) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserWrite) Hub() {}
