/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MicrosoftEntraInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MicrosoftEntraObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MicrosoftEntraParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// MicrosoftEntraSpec defines the desired state of MicrosoftEntra
type MicrosoftEntraSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MicrosoftEntraParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MicrosoftEntraInitParameters `json:"initProvider,omitempty"`
}

// MicrosoftEntraStatus defines the observed state of MicrosoftEntra.
type MicrosoftEntraStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MicrosoftEntraObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MicrosoftEntra is the Schema for the MicrosoftEntras API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type MicrosoftEntra struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MicrosoftEntraSpec   `json:"spec"`
	Status MicrosoftEntraStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MicrosoftEntraList contains a list of MicrosoftEntras
type MicrosoftEntraList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MicrosoftEntra `json:"items"`
}

// Repository type metadata.
var (
	MicrosoftEntra_Kind             = "MicrosoftEntra"
	MicrosoftEntra_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MicrosoftEntra_Kind}.String()
	MicrosoftEntra_KindAPIVersion   = MicrosoftEntra_Kind + "." + CRDGroupVersion.String()
	MicrosoftEntra_GroupVersionKind = CRDGroupVersion.WithKind(MicrosoftEntra_Kind)
)

func init() {
	SchemeBuilder.Register(&MicrosoftEntra{}, &MicrosoftEntraList{})
}
