/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SourceOAuthInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SourceOAuthObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type SourceOAuthParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// SourceOAuthSpec defines the desired state of SourceOAuth
type SourceOAuthSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SourceOAuthParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SourceOAuthInitParameters `json:"initProvider,omitempty"`
}

// SourceOAuthStatus defines the observed state of SourceOAuth.
type SourceOAuthStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SourceOAuthObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SourceOAuth is the Schema for the SourceOAuths API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type SourceOAuth struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   SourceOAuthSpec   `json:"spec"`
	Status SourceOAuthStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SourceOAuthList contains a list of SourceOAuths
type SourceOAuthList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SourceOAuth `json:"items"`
}

// Repository type metadata.
var (
	SourceOAuth_Kind             = "SourceOAuth"
	SourceOAuth_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SourceOAuth_Kind}.String()
	SourceOAuth_KindAPIVersion   = SourceOAuth_Kind + "." + CRDGroupVersion.String()
	SourceOAuth_GroupVersionKind = CRDGroupVersion.WithKind(SourceOAuth_Kind)
)

func init() {
	SchemeBuilder.Register(&SourceOAuth{}, &SourceOAuthList{})
}
