/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Application) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Blueprint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CertificateKeyPair) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EventRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *EventTransport) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Flow) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FlowStageBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Outpost) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ScopeMapping) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceConnectionKubernetes) Hub() {}
