/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ServiceConnectionKubernetesInitParameters struct {

	// (String, Sensitive) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
	KubeconfigSecretRef *v1.SecretKeySelector `json:"kubeconfigSecretRef,omitempty" tf:"-"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Local *bool `json:"local,omitempty" tf:"local,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	VerifySSL *bool `json:"verifySsl,omitempty" tf:"verify_ssl,omitempty"`
}

type ServiceConnectionKubernetesObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	Local *bool `json:"local,omitempty" tf:"local,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	VerifySSL *bool `json:"verifySsl,omitempty" tf:"verify_ssl,omitempty"`
}

type ServiceConnectionKubernetesParameters struct {

	// (String, Sensitive) JSON format expected. Use jsonencode() to pass objects. Defaults to {}.
	// JSON format expected. Use jsonencode() to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	KubeconfigSecretRef *v1.SecretKeySelector `json:"kubeconfigSecretRef,omitempty" tf:"-"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	Local *bool `json:"local,omitempty" tf:"local,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	VerifySSL *bool `json:"verifySsl,omitempty" tf:"verify_ssl,omitempty"`
}

// ServiceConnectionKubernetesSpec defines the desired state of ServiceConnectionKubernetes
type ServiceConnectionKubernetesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ServiceConnectionKubernetesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServiceConnectionKubernetesInitParameters `json:"initProvider,omitempty"`
}

// ServiceConnectionKubernetesStatus defines the observed state of ServiceConnectionKubernetes.
type ServiceConnectionKubernetesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServiceConnectionKubernetesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ServiceConnectionKubernetes is the Schema for the ServiceConnectionKubernetess API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type ServiceConnectionKubernetes struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ServiceConnectionKubernetesSpec   `json:"spec"`
	Status ServiceConnectionKubernetesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServiceConnectionKubernetesList contains a list of ServiceConnectionKubernetess
type ServiceConnectionKubernetesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ServiceConnectionKubernetes `json:"items"`
}

// Repository type metadata.
var (
	ServiceConnectionKubernetes_Kind             = "ServiceConnectionKubernetes"
	ServiceConnectionKubernetes_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ServiceConnectionKubernetes_Kind}.String()
	ServiceConnectionKubernetes_KindAPIVersion   = ServiceConnectionKubernetes_Kind + "." + CRDGroupVersion.String()
	ServiceConnectionKubernetes_GroupVersionKind = CRDGroupVersion.WithKind(ServiceConnectionKubernetes_Kind)
)

func init() {
	SchemeBuilder.Register(&ServiceConnectionKubernetes{}, &ServiceConnectionKubernetesList{})
}
