/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Group) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SourceKerberos) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SourceLDAP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SourceOAuth) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SourcePlex) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SourceSAML) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
